name: Bug report | 问题汇报
description: Any bug can be reported here 可以在这里汇报任何问题。
title: '[Bug]: '
labels:
  - code/bug
assignees:
  - rong-xiaoli
projects: "rong-xiaoli/3"
body:
  - type: textarea
    id: description
    attributes:
      label: Description 描述
      description: A clear and concise description of the problem 对问题的清晰简要的描述
      placeholder: 谁在什么时候发了什么可以导致机器人怎么了
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Minimal Reproduction 最简单复现方法
      description: provide steps to reproduce the problem 如何重复产生这个问题
  - type: textarea
    id: log
    attributes:
      label: Exception or Error 日志上传
      description: provide error logs if you have it 如果你有日志，可以在这里上传
  - type: checkboxes
    id: similarity_check
    attributes:
      label: Similarity check 相似度检查
      description: >-
        可以在[问题(issues)](https://github.com/rong-xiaoli/Elysia/issues?q=is%3Aissue)里看一下有没有相似的问题，如果有的话可以在那个问题底下跟帖催更。
      options:
        - label: >-
            I've done similarity search and this is a new issue.
            我做过了相似搜索，这是个新问题。
          required: true
# Generated by: [Issue Forms Creator](https://issue-forms-creator.netlify.app)


