name: Code enhance | 代码改进
description: Enhancement for code. 代码能写得更好。
title: '[Enha]: '
labels:
  - code/enhancement
assignees:
  - rong-xiaoli
projects: "rong-xiaoli/3"
body:
  - type: textarea
    id: EnhancemetSource
    attributes:
      label: Enhancement source code 原来的源码
      description: The code which can be enhanced. 代码哪里可以改进
      placeholder: >-
        https://github.com/rong-xiaoli/Elysia/blob/f41c0472cb81c0d8f71d0a4131e6c9e7d88fdfba/README.md?plain=1#L1
    validations:
      required: true
  - type: textarea
    id: EnhancementCode
    attributes:
      label: Enhancement code or implement method 改好的代码或改动方式
      description: What should it look like 它应该怎么写
      placeholder: it should be like this blah blah blah
      render: Java
    validations:
      required: true
  - type: checkboxes
    id: similarity_check
    attributes:
      label: Similarity check 相似度检查
      description: >-
        可以在[问题(issues)](https://github.com/rong-xiaoli/Elysia/issues?q=is%3Aissue)里看一下有没有相似的问题，如果有的话可以在那个问题底下跟帖催更。
      options:
        - label: >-
            I've done similarity search and this is a new issue.
            我做过了相似搜索，这是个新问题。
          required: true
# Generated by: [Issue Forms Creator](https://issue-forms-creator.netlify.app)
